name: Deploy to Heroku Frontend

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Install Heroku CLI
      - name: Install Heroku CLI
        run: |
          curl https://cli-assets.heroku.com/install.sh | sh
          heroku --version

      # 3. Set up Heroku authentication
      - name: Set up Heroku auth
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
          HEROKU_EMAIL: ${{ secrets.HEROKU_EMAIL }}
        run: |
          echo "machine api.heroku.com" > ~/.netrc
          echo "  login $HEROKU_EMAIL" >> ~/.netrc
          echo "  password $HEROKU_API_KEY" >> ~/.netrc
          echo "machine git.heroku.com" >> ~/.netrc
          echo "  login $HEROKU_EMAIL" >> ~/.netrc
          echo "  password $HEROKU_API_KEY" >> ~/.netrc
          chmod 600 ~/.netrc
          heroku auth:whoami

      # 4. Build & Deploy Frontend to Heroku
      - name: Build & Deploy Frontend to Heroku
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
          HEROKU_APP_NAME_FE: ${{ secrets.HEROKU_APP_NAME_FE }}
        run: |
          cd frontend
          echo "Contenu de frontend :"
          ls -la
          heroku container:login
          docker build . --platform linux/amd64 -t registry.heroku.com/$HEROKU_APP_NAME_FE/web
          docker push registry.heroku.com/$HEROKU_APP_NAME_FE/web
          heroku container:release web --app $HEROKU_APP_NAME_FE

      # 5. Set Frontend Heroku config vars
      - name: Set Frontend Heroku config vars
        env:
          HEROKU_APP_NAME_FE: ${{ secrets.HEROKU_APP_NAME_FE }}
          HEROKU_APP_NAME_BE: ${{ secrets.HEROKU_APP_NAME_BE }}
        run: |
          heroku config:set API_BASE_URL=https://${HEROKU_APP_NAME_BE}.herokuapp.com --app $HEROKU_APP_NAME_FE
          heroku config:set ENVIRONMENT=production --app $HEROKU_APP_NAME_FE

      # 6. Show Frontend Heroku logs (utile pour déboguer)
      - name: Show Frontend Heroku logs
        env:
          HEROKU_APP_NAME_FE: ${{ secrets.HEROKU_APP_NAME_FE }}
        run: |
          heroku logs --app $HEROKU_APP_NAME_FE --num 100

      # Stop Heroku Dynos (désactivé par défaut)
      - name: Stop Heroku Dynos
        if: ${{ false }} # Active en changeant en 'true'
        run: |
          heroku ps:scale web=0 --app ${{ secrets.HEROKU_APP_NAME_FE }}