name: Deploy Frontend to Heroku

on:
  push:
    branches:
      - main

jobs:
  deploy-frontend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Heroku CLI
        run: |
          curl https://cli-assets.heroku.com/install.sh | sh
          heroku --version

      - name: Set up Heroku authentication
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
          HEROKU_EMAIL: ${{ secrets.HEROKU_EMAIL }}
        run: |
          echo "machine api.heroku.com" > ~/.netrc
          echo "  login $HEROKU_EMAIL" >> ~/.netrc
          echo "  password $HEROKU_API_KEY" >> ~/.netrc
          echo "machine git.heroku.com" >> ~/.netrc
          echo "  login $HEROKU_EMAIL" >> ~/.netrc
          echo "  password $HEROKU_API_KEY" >> ~/.netrc
          chmod 600 ~/.netrc
          heroku auth:whoami

      - name: Clean Docker builder cache (optional)
        run: docker builder prune -a -f

      - name: Build & Deploy Frontend to Heroku
        env:
          HEROKU_APP_NAME_FE: ${{ secrets.HEROKU_APP_NAME_FE }}
        run: |
          cd frontend
          heroku stack:set container --app $HEROKU_APP_NAME_FE
          heroku container:login
          docker build . --platform linux/amd64 -t registry.heroku.com/$HEROKU_APP_NAME_FE/web
          docker push registry.heroku.com/$HEROKU_APP_NAME_FE/web
          heroku container:release web --app $HEROKU_APP_NAME_FE

      - name: Set Frontend Heroku config vars
        env:
          HEROKU_APP_NAME_FE: ${{ secrets.HEROKU_APP_NAME_FE }}
          HEROKU_APP_NAME_BE: ${{ secrets.HEROKU_APP_NAME_BE }}
        run: |
          heroku config:set \
            API_BASE_URL=https://${HEROKU_APP_NAME_BE}.herokuapp.com \
            ENVIRONMENT=production \
            --app $HEROKU_APP_NAME_FE

      - name: Show Frontend Heroku logs (optional)
        env:
          HEROKU_APP_NAME_FE: ${{ secrets.HEROKU_APP_NAME_FE }}
        run: heroku logs --app $HEROKU_APP_NAME_FE --num 100

      # Stop Heroku Dynos (désactivé par défaut)
      - name: Stop Heroku Dynos
        if: ${{ false }} # Active en changeant en 'true'
        run: |
          heroku ps:scale web=0 --app ${{ secrets.HEROKU_APP_NAME_FE }}